//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.cpp
//  @ Date : 25.05.2023
//  @ Author : 
//
//


#include "Kurs.h"
#include <iostream>

void Kurs::Wyswietl() {
    std::cout << "Nazwa kursu: " << Nazwa << std::endl;
    for(int i=0;i<Tematy.size();i++){
        std::cout <<i+1<<". "  + Tematy[i] << std::endl;
    }
}

