//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kurs.h
//  @ Date : 25.05.2023
//  @ Author : 
//
//


#if !defined(_KURS_H)
#define _KURS_H


class Kurs {
public:
	string Nazwa;
	tab Tematy;
    vector<Student, Long> oceny;
    vector<Student> studenci;
	void Wyswietl();
};

#endif  //_KURS_H
