//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ocena.h
//  @ Date : 13.06.2023
//  @ Author : 
//
//


#if !defined(_OCENA_H)
#define _OCENA_H


class Ocena {
public:
	int ocena;
	int studentId;
	Ocena();
};

#endif  //_OCENA_H
