//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 25.05.2023
//  @ Author : 
//
//


#include "Student.h"

Student::Student() {

}

Student::~Student() {

}

void Student::SprawdzKursy() {

}

void Student::ZapiszSieNaKurs(int n) {

}

void Student::SprawdzOceny() {

}

