//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 25.05.2023
//  @ Author : 
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H
#include "Student.h"


class Student {
public:
	string studentName;
	int id;
	string login;
	string haslo;
	Student();
	~Student();
	void SprawdzKursy();
	void ZapiszSieNaKurs(int n);
	void SprawdzOceny();
};

#endif  //_STUDENT_H
