//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 25.05.2023
//  @ Author : 
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H
#include <string>

class Student {
public:
    std::string studentName;
    int id;
    std::string login;
    std::string haslo;
    Student();
    ~Student();
    void SprawdzKursy();
    void ZapiszSieNaKurs(int n);
    void SprawdzOceny();
};

#endif  //_STUDENT_H
