//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczelnia.cpp
//  @ Date : 25.05.2023
//  @ Author : 
//
//


#include "Uczelnia.h"

void Uczelnia::setData(string name) {
    nazwa = name;
}

