//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.cpp
//  @ Date : 25.05.2023
//  @ Author : 
//
//


#include "Wykladowca.h"

Wykladowca::Wykladowca() {
    name = "null";
    login = "null";
    haslo = "null";
}

Wykladowca::~Wykladowca() {

}

Kurs Wykladowca::UtworzKurs(const std::string& name) {
    Kurs nowyKurs;
    nowyKurs.Nazwa = name;
    std::cout << "Utworzono nowy kurs: " << name << std::endl;
    this->nazwyKursow.push_back(name);
    return nowyKurs;
}

void Wykladowca::ModyfikujKurs(Kurs kurs) {
    std::string newName;
    std::vector<std::string> newTematy;
    std::cout<<"Czy chcesz zmienić nazwe kursu T/N?"<<std::endl;
    std::string zmiana;
    std::cin>>zmiana;
    if(zmiana == "T" || zmiana == "t") {
        std::cout<<"Podaj nową nazwę kursu: "<<std::endl;
        std::cin>>newName;
    }
    if (!newName.empty()) {
        kurs.Nazwa = newName;
        std::cout << "Zmieniono nazwe kursu na: " << newName << std::endl;
    }
    std::cout<<"Czy chcesz zmienić tematy kursu T/N?"<<std::endl;
    std::cin>>zmiana;
    if(zmiana == "T" || zmiana == "t") {
        kurs.Tematy.clear();
        std::cout<<"Podaj nowe tematy kursu: "<<std::endl;
        std::string temat;
        while(temat != "0") {
            std::cin>>temat;
            if(temat != "0") {
                newTematy.push_back(temat);
            }
        }
    }
}


void Wykladowca::WystawOcene(Kurs kurs, int studentId, int ocena) {
    for (int student : kurs.studentId) {
        if (student == studentId) {
            kurs.oceny.emplace_back(studentId, ocena); // Dodanie elementu na końcu wektora oceny
            std::cout << "Wystawiono ocenę " << ocena << " dla studenta o ID: " << studentId << " w kursie " << kurs.Nazwa << std::endl;
            return;
        }
    }
    std::cout << "Nie znaleziono studenta o ID: " << studentId << " w kursie " << kurs.Nazwa << std::endl;
}



