//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.cpp
//  @ Date : 25.05.2023
//  @ Author : 
//
//


#include "Wykladowca.h"

Wykladowca::Wykladowca() {

}

Wykladowca::~Wykladowca() {

}

void Wykladowca::UtworzKurs(string name) {

}

void Wykladowca::ModyfikujKurs(Kurs kurs) {

}

void Wykladowca::WystawOcene(Kurs kurs, int studentId, int ocena) {

}

void Wykladowca::DodajDoKursu(Kurs kurs, Student student) {

}


