//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.h
//  @ Date : 25.05.2023
//  @ Author : 
//
//


#if !defined(_WYKLADOWCA_H)
#define _WYKLADOWCA_H
#include "Kurs.h"

class Wykladowca {
public:
	string Name;
	string login;
	string haslo;
	Wykladowca();
	~Wykladowca();
	void UtworzKurs(name string);
	void ModyfikujKurs(Kurs kurs);
	void WystawOcene(Kurs kurs, Long studentId, Long ocena);
	void DodajDoKursu(Kurs kurs, id Student);
};

#endif  //_WYKLADOWCA_H
